### ISSUE TITLE
Price incorrect for some stocks

### ISSUE THREAD

**Issue by kezida** [entreprenrisk/FCO-Issues#79]
Royal Dutch Mail:
![image](https://user-images.githubusercontent.com/11725116/95162450-55475280-07d8-11eb-97c6-6375ae65b502.png)

Apple:
![image](https://user-images.githubusercontent.com/11725116/95162554-832c9700-07d8-11eb-99cf-127e64e43958.png)

**Comment by chahat** [comment]
Fixed with fcoReload # 5ee8af6 7cbdf4b 314ddf7 b4c67e0

1) Add check for price adjustment When last price does not match what is stored in the db we delete that price series and fetch it again..
2) Also store the stime of price series so that it can be used in the min of priceChart in frontend STILL PENDING: Check if CMC is also adjusting prices of currencies in which case refetch the price series same as in normal asset.
3) also remove the chr_res/restime for assets with price adjustment as the res becomes invalid. Before the adjustment ABC keep memory of the price and after the adjustment, the adjustment will become part of the fit calculation. hence need to recalculate the whole series
